meta:
  # Classic favicon formats
  favicon_ico: /favicon/favicon.ico
  favicon_svg: /favicon/favicon.svg
  favicon_96: /favicon/favicon-96x96.png

# Progressive web app icons 
manifest: /favicon/manifest.json

# Default Open Graph image
og_image: /images/og/mkm_og_logo.png

# Section Toggles
disable_theme_toggle: true
disable_p2: false
disable_stay_uptodate: true

# Colors
theme_color: "#a2d3db"
background_color: "#ffffff"

# Index / Home Defaults
author: Matthew Miller
authorimage: images/global/author.webp
description: "Home"

welcome:
  heading: "Hi, I'm Matt..."
  subheading: "...and this is Matty Kakes Makes!"
  description: "The digital garage where code meets chaos, CAD meets caffeine, and half-baked ideas somehow turn into working(ish) projects."

p1:
  heading: "What you'll find here..."
  image: "images/pages/matt_saas_almagel_2024.jpg"
  image_quality: 35
  content:
    - text: "The goal isn’t always to make something perfect — it’s to use building as a creative outlet, a way to express ideas in physical form. Sometimes that means making something surprisingly useful, other times it means creating something delightfully absurd. Either way, every build is a chance to experiment, learn, and turn imagination into something you can actually hold in your hands."
    - text: "Engineering Projects - From software to hardware, this is where code, circuits, and machines collide. Expect projects that range from practical tools to strange experiments that maybe shouldn’t work… but somehow do."
    - text: "Technical Blogs - Deep dives, lessons learned, and professional opinions. These posts are equal parts documentation, storytelling, and lessons learn from both personal and professional experiences."
    - text: "Creative Builds - This is where ideas take a playful detour. Some projects are practical, others are purely for fun, and a few land somewhere in between."

p2:
  heading: Why "Matty Kakes"?
  image: images/pages/index_failed_cake_1_mkm.png
  image_quality: 50
  content:
    - text: "Because every project is a bit like a cake: you start with a recipe, throw in your own flavor, and hope it doesn’t collapse in the oven. And if it does? Well, that’s part of the fun."
    - text: "Mistakes aren’t just inevitable — they’re the secret ingredient. Every time something wobbles, sparks, or fails spectacularly, it leaves behind a lesson. Maybe it’s about how a something actually works (or doesn’t), maybe it’s about why that “clever shortcut” wasn’t so clever after all. Either way, those stumbles are where the real learning happens."
    - text: "The truth is, nothing creative comes out perfect the first time. Trial and error isn’t just normal — it’s the engine that drives better ideas. The failures shape the successes, and the detours often lead to the most interesting results."
